### ISSUE TITLE
Add Motion Controls to Switch Joy-Con

### ISSUE THREAD

**Issue by DanilochTop** [GaryOderNichts/Bloopair#133] opened 2024-04-20 20:58 UTC
As a poor fan of Nintendo games, I don't have the money to buy more controllers and batteries for them.
So I think It would be great if we had a plugin option to set the joy-cons to emulate a wii remote, not necessarily for the vWii, but for the Wii U games that require a wii controller.
Since the switch has everything that's needed for motion detection, I think this would make the job of implementation a lot easier.
As well, many people would like it (including me), because we could invite more friends to come play :)

**Comment by GaryOderNichts** [comment] 2024-06-04 23:17
Duplicate of #26.

**Closed by GaryOderNichts** 2024-06-04 23:17 UTC
