### ISSUE TITLE
Bloopair v0.6.1 is interfering with the first pairing of the Wii Remote

### ISSUE THREAD

**Issue by cleberjorge** [GaryOderNichts/Bloopair#89] opened 2023-02-04 08:41 UTC
Bloopair v0.6.1 is interfering with the first pairing of the Wii Remote
When I deleted the 30_bloopair.rpx file, it stopped the control normally

**Comment by GaryOderNichts** [comment] 2023-02-04 11:50
Duplicate of #56?

**Comment by GaryOderNichts** [comment] 2023-02-05 01:38
Oh yeah I can reproduce this even with official remotes. Looks like 0.6.X broke something.

**Comment by GaryOderNichts** [comment] 2023-02-05 01:50
Please test the following build: [Bloopair_nightly.zip](https://nightly.link/GaryOderNichts/Bloopair/workflows/ci/main/Bloopair_nightly.zip)

**Comment by GaryOderNichts** [comment] 2023-02-06 18:29
Fixed with version 0.6.2.

**Closed by GaryOderNichts** 2023-02-06 18:29 UTC
Labels: bug
