### ISSUE TITLE
A Quick Suggestion (For Next Update Possibly).

### ISSUE THREAD

**Issue by Walegy** [GaryOderNichts/Bloopair#102] opened 2023-05-07 00:08 UTC
I have a crazy good suggestion that was offered here in issues, yet I am not sure if it has been implemented... Personally, I would like to see audio support for headphone jacked controllers that connect through Bloopair! It would be intruiging to see this implemented, as well as having a way to connect the headphone jack other than the Gamepad.

**Comment by GaryOderNichts** [comment] 2024-06-04 23:29
Duplicate of #62.

**Closed by GaryOderNichts** 2024-06-04 23:29 UTC
