### ISSUE TITLE
Suggestion regarding possible Gamepad support

### ISSUE THREAD

**Issue by Bluestk** [GaryOderNichts/Bloopair#147] opened 2024-08-12 03:07 UTC
This isn't exactly an issue but idk where else I could post this but I was wondering if it would be maybe possible for your to add support for controllers to emulate the Wii U Gamepad instead of a Pro Controller in the future, as my Gamepad screen is working fine but the sticks have been broken for a while, which makes it so I can't play stuff that needs it, and the only program that has anything of the sort hasn't been updated for Aroma at all, and with you adding new configuration, could that maybe be an option? Thank you very much again for the program!

**Comment by GaryOderNichts** [comment] 2024-08-12 17:56
This is a duplicate of #33 and currently not a planned feature.

**Closed by GaryOderNichts** 2024-08-12 17:56 UTC
