### ISSUE TITLE
NSO N64 Controller Screenshot Button is X Button

### ISSUE THREAD

**Issue by Randanyo** [GaryOderNichts/Bloopair#96] opened 2023-03-17 13:21 UTC
When using the Screenshot Plugin from WiiUPluginLoader, the Switch Pro Controller Screenshot Button takes photos just fine. But when using the NSO N64 Switch Controller, I noticed that it outputs as the X Button. 
Unsure if this is a WiiUPluginLoader issue or Bloopair, but when using Controller Test homebrew app, the NSO N64 Switch Screenshot button also picks up as the X Button. 
Anyone else having this issue? I'm on Aroma. 
![PXL_20230317_131852996](https://user-images.githubusercontent.com/121588081/225916068-52e24dcd-de58-4c70-ae1a-921fef0d0dd0.jpg)
![PXL_20230317_131855242](https://user-images.githubusercontent.com/121588081/225916073-0fa7f356-9c77-40fa-925d-c7af6ebde508.jpg)

**Comment by vaguerant** [comment] 2023-08-01 06:14
This is the intended behavior on the N64 controller, you can see it's explicitly commented as such in the code:

https://github.com/GaryOderNichts/Bloopair/blob/7baf11960a60b4e738870299c9058799993596dd/ios/ios_pad/source/controllers/switch_controller.c#L447-L449

If I had to guess, it's because you need an X button to properly navigate the Wii U Menu with Pro Controller, since it's used to swap between Warawara Plaza and the channel list. Ideally, this could be resolved by allowing users to set their own custom button mappings on Bloopaired controllers, but for now we probably just have to either deal with it or customize and build the plugin locally.

**Comment by IceBlueLugia** [comment] 2023-09-08 17:24
Could it be set to the TV button for screenshots maybe? It’s not very important issue, but I figure it’s worth asking if it’s possible

**Comment by GaryOderNichts** [comment] 2024-07-20 09:37
[Bloopair v1.0.0](https://github.com/GaryOderNichts/Bloopair/releases/tag/v1.0.0) supports button remapping.

**Closed by GaryOderNichts** 2024-07-20 09:37 UTC
Labels: enhancement
